# Generated by Django 5.2.11 on 2026-02-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Název vybavení (např. X32)')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Výchozí cena za akci')),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název akce')),
                ('date', models.DateField(verbose_name='Datum konání')),
                ('client_name', models.CharField(max_length=200, verbose_name='Klient')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámky')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GigEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Počet kusů')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sjednaná cena za kus')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.equipment')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_used', to='app.gig')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('TRV', 'Cesta (Travel)'), ('SET', 'Příprava (Setup)'), ('SND', 'Zvučení (Sound)'), ('TDR', 'Bourání (Teardown)')], default='SND', max_length=3)),
                ('start_time', models.DateTimeField(verbose_name='Čas OD')),
                ('end_time', models.DateTimeField(verbose_name='Čas DO')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sazba (Kč/h)')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_phases', to='app.gig')),
            ],
        ),
    ]
