# Generated by Django 5.2.11 on 2026-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workphase',
            name='hourly_rate',
            field=models.IntegerField(choices=[(250, '250 Kč/h'), (300, '300 Kč/h'), (350, '350 Kč/h'), (400, '400 Kč/h'), (450, '450 Kč/h'), (500, '500 Kč/h')], default=250, verbose_name='Sazba (Kč/h)'),
        ),
        migrations.AlterField(
            model_name='workphase',
            name='phase',
            field=models.CharField(choices=[('TRV', 'Cesta (Travel)'), ('SET', 'Příprava (Setup)'), ('SND', 'Zvučení (Sound)'), ('TDR', 'Bourání (Teardown)')], default='SND', max_length=3, verbose_name='Fáze'),
        ),
    ]
