# Generated by Django 5.2.11 on 2026-02-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gig_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název / Jméno')),
                ('ico', models.CharField(blank=True, max_length=20, null=True, verbose_name='IČO')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámka ke klientovi')),
            ],
        ),
        migrations.RemoveField(
            model_name='gig',
            name='client_name',
        ),
        migrations.AddField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('planned', 'V plánu'), ('ongoing', 'Probíhá'), ('done', 'Hotovo')], default='planned', max_length=20, verbose_name='Stav'),
        ),
        migrations.AddField(
            model_name='gig',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Klient'),
        ),
    ]
