# Generated by Django 5.2.11 on 2026-02-26 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_client_remove_gig_client_name_gig_status_gig_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Jméno a příjmení')),
                ('ico', models.CharField(blank=True, max_length=20, null=True, verbose_name='IČO')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo účtu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
        ),
    ]
