# Generated by Django 5.2.11 on 2026-02-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_alt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo účtu'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN'),
        ),
    ]
