# Generated by Django 6.0.5 on 2026-05-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_client_address_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('planned', 'V plánu'), ('ongoing', 'Probíhá'), ('done', 'Hotovo'), ('paid', 'Zaplaceno')], default='planned', max_length=20, verbose_name='Stav'),
        ),
        migrations.CreateModel(
            name='CustomInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Popis položky')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Množství')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Jednotka (ks, den, apod.)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Jednotková cena')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_items', to='app.gig')),
            ],
            options={
                'verbose_name': 'Vlastní položka na faktuře',
                'verbose_name_plural': 'Vlastní položky na faktuře',
                'ordering': ['id'],
            },
        ),
    ]
