# Generated by Django 6.0.5 on 2026-05-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_gig_status_custominvoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custominvoiceitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='custominvoiceitem',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fixní cena (Kč)'),
        ),
        migrations.AddField(
            model_name='custominvoiceitem',
            name='item_type',
            field=models.CharField(choices=[('fixed', 'Fixní cena'), ('hourly', 'Hodinová sazba')], default='fixed', max_length=10, verbose_name='Typ položky'),
        ),
        migrations.AlterField(
            model_name='custominvoiceitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, null=True, verbose_name='Počet hodin'),
        ),
        migrations.AlterField(
            model_name='custominvoiceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cena za hodinu (Kč/h)'),
        ),
    ]
