# Generated by Django 6.0.5 on 2026-07-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_custominvoiceitem_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uloženo')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Číslo faktury')),
                ('work_phases_data', models.JSONField(default=list, verbose_name='Snapshot pracovních fází')),
                ('equipment_data', models.JSONField(default=list, verbose_name='Snapshot techniky')),
                ('custom_items_data', models.JSONField(default=list, verbose_name='Snapshot vlastních položek')),
                ('total_work_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za práci')),
                ('total_equipment_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za techniku')),
                ('total_custom_items_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za ostatní')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Celková cena')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_snapshots', to='app.gig', verbose_name='Akce')),
            ],
            options={
                'verbose_name': 'Snapshot faktury',
                'verbose_name_plural': 'Snapshoty faktur',
                'ordering': ['-created_at'],
            },
        ),
    ]
